### ISSUE TITLE
New Api url

### ISSUE THREAD

**Issue by adeshinichi** [vHack-API/vHackAPI-Java#10]
Api url changed to api.vhack.cc please update it.... And i think this code need to updated based on current vhack app

**Comment by checkium** [comment]
The code changes will be committed soon, The devs are working on it.

Em 11/11/2016 09:36, "adeshinichi" <notifications@github.com> escreveu:

**Comment by Cryoplex** [comment]
Any updates or details on who is working on it? I don't see a fork.

**Comment by checkium** [comment]
Currently I'm busy with other personal things so I dont have time to do it, The other dev doesnt come online since 1 week ago. So I dont know what I can do.

**Comment by Qup42** [comment]
I´ve added a pull request which changes the url to the newest version.

**Comment by Cryoplex** [comment]
Once the URL has changed, what parts of the API still persist to function?

**Comment by Qup42** [comment]
With the new URL everything except for the Adware(it was removed from the game) should work again.

**Comment by checkium** [comment]
Things may or may not work @Qup42 @Cryoplex  Only testing, debugging and decompiling can verify it.

**Comment by Qup42** [comment]
The hashing code in this Repo was (except some readabilty improvements) the same to the hashing code I decompiled from the newest Version (1.35).

**Comment by checkium** [comment]
Yes but there can be changes on each thing, some URL may need more arguments or less

**Comment by dude24760** [comment]
Well I've just looked at the decompiled APK, and it seems the dev has cleared up the code quite a bit. A lot less files. it seems he's quite nicely named the URL builder as "RequestHelper.java", so it's easier to find in future updates. As for the new API url, it's currently "https://api.vhack.cc/v/5/". The secret is still "aeffl". It's been a while since I last made a contribution to the unofficial API, so I'm a little rusty when it comes to remembering how the URL was made in the API. However, if simply changing the API url to the one above doesn't work, then the problem might lie in the generation of the pass variable. I'm not entirely sure, but it seems there's been modifications to the JSON. 

 String string = sharedPreferences.getString("strUser", "");
 String string2 = sharedPreferences.getString("strPass", "");
 String string3 = sharedPreferences.getString("uhash", "");

And then there's:
jSONObject.put("time", currentTimeMillis + "");
jSONObject.put("user", string);
jSONObject.put("pass", string2);
jSONObject.put("uhash", string3);

I don't recall "uhash" being part of the JSON, and I can't load up my Android VM and check the packets, but keep in mind this might just be my bad memory.

A sample call from the ConsoleActivity.java would be:

HttpURLConnection httpURLConnection = (HttpURLConnection) new URL(RequestHelper.m9375a(this.f5218a.getApplicationContext(), "target", strArr[0], "vh_scan.php")).openConnection();

Where "RequestHelper.m9375a" is the function that generates the URL. In this case, strArr[0] seems to be the target IP for the scan. There seems to be no change as to how the response to this request is interpreted. 

Well, that's all. Checkium has the updated API code, and I don't, so I can't test any of this.

**Comment by Qup42** [comment]
@dude24760 
Yes thats right. Up to today there were to new updates which means that the URL now is "https://api.vhack.cc/v/7/". There have been changes with how bonus boxes and boosters work.
I looked at your code and it'd be a lot of work to transfer it to your classes because your style (which is cleaner than mine) requires a lot more changes.

**Comment by Cryoplex** [comment]
@Qup42
When will we be expecting yours to go open source?

**Comment by Qup42** [comment]
@Cryoplex I'm integrating the changes in the fork I did so that this api will work again. You can find it on my profile.

**Comment by checkium** [comment]
@Qup42 Feel free to pull request when you are done :)
