### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ghost** [vHack-API/vHackAPI-Java#14]
If you scan or transfer on more than one ip the application crashes. I figured out that if you manually use the http request in your browser and spamming F5 you get a 404 Response. However if you delay for exactly 3000ms after every single scan + transfer and loop it, it works fine.

Any way to fix this or is it a thing with the vhack servers ?

here is a little trash example for console:
http://pastebin.com/tC50epND

**Comment by itsfolf** [comment]
Hi @tr0teK , thats something about your own code, you should never scan multiple IPs at the same time, since that will result in a ban that could be avoided. that already happened one time, where a friend used the API too fast, scan like 10 ips per second, and his account got locked.

**Comment by ghost** [comment]
Hey @checkium. Then why is the API built for multiple scans and transfers at the same time ? It's working with Lists. Wouldn't it be better to rewrite the API to work with one IP at the time instead with all the loops and Lists ?

**Comment by itsfolf** [comment]
Hi again @tr0teK, when the API was made there wasnt' any problems of doing multiple requesets at the same time, they just needed a 300ms delay (that exists currently), but vHack devs seem to have added some more "anti-bot" protection. Currently who is working on the API is @Qup42 since I'm busy with school things and dont have time to update it, but I'm planning to do the API 1.0 version on vacation (17 December - 2 January), I have telled him about this issue, now it's with him. If you have any further problems, you can chat with us over discord, invite is located at readme.
